# --- !Ups

CREATE TABLE message (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  message TEXT NOT NULL,
  destination VARCHAR(255) NOT NULL,
  message_type VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP /*! ON UPDATE CURRENT_TIMESTAMP  */,
  PRIMARY KEY (id)
);


# --- !Downs

DROP TABLE message;
